# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import seguimientos_pb2 as grpc__client_dot_seguimientos__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_client/seguimientos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeguimientosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerSeguimientosProcesados = channel.unary_unary(
                '/seguimientos.SeguimientosService/ObtenerSeguimientosProcesados',
                request_serializer=grpc__client_dot_seguimientos__pb2.SeguimientosRequest.SerializeToString,
                response_deserializer=grpc__client_dot_seguimientos__pb2.SeguimientosResponse.FromString,
                _registered_method=True)


class SeguimientosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerSeguimientosProcesados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeguimientosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerSeguimientosProcesados': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerSeguimientosProcesados,
                    request_deserializer=grpc__client_dot_seguimientos__pb2.SeguimientosRequest.FromString,
                    response_serializer=grpc__client_dot_seguimientos__pb2.SeguimientosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seguimientos.SeguimientosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seguimientos.SeguimientosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeguimientosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerSeguimientosProcesados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seguimientos.SeguimientosService/ObtenerSeguimientosProcesados',
            grpc__client_dot_seguimientos__pb2.SeguimientosRequest.SerializeToString,
            grpc__client_dot_seguimientos__pb2.SeguimientosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
