# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_client/seguimientos.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_client/seguimientos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_client/seguimientos.proto\x12\x0cseguimientos\"1\n\x13SeguimientosRequest\x12\x1a\n\x12usuarios_idusuario\x18\x01 \x01(\t\"G\n\x14SeguimientosResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x11\n\tcreadores\x18\x02 \x03(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2}\n\x13SeguimientosService\x12\x66\n\x1dObtenerSeguimientosProcesados\x12!.seguimientos.SeguimientosRequest\x1a\".seguimientos.SeguimientosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_client.seguimientos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEGUIMIENTOSREQUEST']._serialized_start=48
  _globals['_SEGUIMIENTOSREQUEST']._serialized_end=97
  _globals['_SEGUIMIENTOSRESPONSE']._serialized_start=99
  _globals['_SEGUIMIENTOSRESPONSE']._serialized_end=170
  _globals['_SEGUIMIENTOSSERVICE']._serialized_start=172
  _globals['_SEGUIMIENTOSSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
